### ISSUE TITLE
Shib wreaking havoc with XHR

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/rialto-webapp#309]
I don't have it fully reproducible but seeing like this:
<img width="1290" alt="screen shot 2019-01-28 at 12 23 52 pm" src="https://user-images.githubusercontent.com/588335/51853995-a7438f80-22f7-11e9-8126-b1f2b709fa1b.png">

**Comment by justinlittman** [comment]
Also:
<img width="1483" alt="screen shot 2019-01-28 at 12 42 52 pm" src="https://user-images.githubusercontent.com/588335/51855053-4d909480-22fa-11e9-8e6a-b40f4e4acfa2.png">

**Comment by jonrober** [comment]
I haven't done anything with XHR and don't know the program flow there.  Could you fill in more of what exactly is happening there?  I see another ticket about this after a time when you've logged in.  Is this the same case?  That one would probably be the session duration running out, and I can check on the default and extend it if that's still a problem.

**Comment by jcoyne** [comment]
The problem here is that the javascript is expecting to make a request to the rialto server for some json, but it gets redirected to https://login.stanford.edu, and it gets blocked because login.stanford.edu doesn't set the correct CORS headers that the javascript is expecting.

I believe the problem is that Apache is just redirecting to login.stanford.edu even when the Accept header does not include `text/html`.  In that case it probably should just be returning a 401 or something like that.

**Comment by jonrober** [comment]
The default we're setting is 8 hours, though it's possible that the central UIT servers are forcing a shorter lifetime.  Do you have an idea of what the duration seems to be in your experience?

**Comment by jonrober** [comment]
When is the javascript hitting that error -- every time, or just after some time has gone on?  I'm not sure if we can do something like having it return a 401 specifically in that case, since that's just how the shibboleth flow works.  I could tell Apache to return a 401 for everything where the accept header isn't text/html, but I don't think that I can insert into that logic into the middle of the shibboleth flow, to tell it to just return a 401 for specific headers rather than actually trying to auth.  I'll try to find any ways to do so, but I doubt there would be.

Could you see if https://stackoverflow.com/questions/36316574/getting-cors-error-with-saml-2-0 is relevant to you?

**Comment by justinlittman** [comment]
Sorry I didn't respond earlier, but I was traveling. I believe this is different than #289, as it occurs in the midst of using the site, not after waiting for the session to expire.

I noticed this because I've been watching the network traffic in the browser with developer tools. I haven't been able to figure out a way to reproduce the problem consistently.

I don't believe setting no cache will solve the problem, as this is happening mid-session.

But, let me see if I can come up with a consistent way of reproducing.

**Comment by justinlittman** [comment]
Happened to me again this morning. It was on a tab that had sat overnight, but then I refreshed (splat R) and then selected the catalog page.

<img width="1488" alt="screen shot 2019-01-29 at 6 32 23 am" src="https://user-images.githubusercontent.com/588335/51905692-e1f90680-238f-11e9-9dfd-7ce66786b317.png">

**Comment by justinlittman** [comment]
You can see I was originally bounced to shib.

<img width="1183" alt="screen shot 2019-01-29 at 6 35 51 am" src="https://user-images.githubusercontent.com/588335/51905792-37cdae80-2390-11e9-84b4-c594d0bcc483.png">

**Comment by jcoyne** [comment]
There are several 5xx errors in the shib ALB: https://us-west-2.console.aws.amazon.com/cloudwatch/home?region=us-west-2#metricsV2:graph=~(view~'timeSeries~stacked~false~region~'us-west-2~start~'-PT3H~end~'P0D~metrics~(~(~'AWS*2fApplicationELB~'HTTPCode_Target_5XX_Count~'LoadBalancer~'app*2frialto-staging-shib-alb*2ffa847d30b774ba02)~(~'.~'HTTPCode_ELB_5XX_Count~'.~'.)));search=~'shib;namespace=~'AWS*2fApplicationELB;dimensions=~'LoadBalancer

And in the logs (https://us-west-2.console.aws.amazon.com/cloudwatch/home?region=us-west-2#logStream:group=rialto-staging)  I see:
```
sp-native 2019-01-29 14:28:52 WARN Shibboleth.ServiceProvider [1205] shib_check_user: error during session lookup: Your IP address (10.0.1.77) does not match the address recorded at the time the session was established.
sp-shibd 2019-01-29 14:28:52 INFO Shibboleth.SessionCache [83]: removed session (_4c35424ba6772bc3e07d6a6f49f807cd)
```
I think it's looking at the LB ip, and not the source IP.
so, when you get routed through a different LB node, it kills your session.

**Comment by justinlittman** [comment]
With fix, now works for me.
